#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Checking all the things before committing'

# Check tsconfig for type check errors
npm run check-types ||
(
    echo 'Type Check Failed. Make the changes listed above and try commit again.'
    false;
)

npm run testFinal ||
(
    echo 'Test Failed. Checking failing test listed above and try commit again.'
)

npx lint-staged
