name: Production Release
on:
  release:
    types: [published]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint Checker
        run: pnpm lint

      - name: Run Type Checker
        run: pnpm typecheck

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Format Checker
        run: pnpm format

  update-production:
    name: Update Production Mobile App
    needs: [test, format, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: pnpm install

      - name: Publish Production App Update
        run: cd apps/expo && APP_ENV=production eas update --environment production --branch production --message "${{ github.ref_name }}"
